image: golang:1.13

stages:
    - test

services:
  - postgres:12

variables:
  POSTGRES_DB: pgqueue
  POSTGRES_USER: pgqueue
  POSTGRES_PASSWORD: ""
  PGQUEUE_TEST_ENABLED: "true"
  PGQUEUE_TEST_BASE_DB: pgqueue
  PGQUEUE_TEST_POSTGRES_CONNSTRING_PATTERN: "postgres://pgqueue@postgres/%s?sslmode=disable" 

test:
    stage: test
    script:
      - git config --global credential.helper store
      - echo 'https://tcard:mtitALP1wFDVLxPn86dc@gitlab.com' >> ~/.git-credentials
      - go test -race -v $(go list ./... | grep -v /vendor/)
