// Code generated by "stringer -type msg ."; DO NOT EDIT.

package itersess

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[msgPullerDone-0]
	_ = x[msgGiverDone-1]
	_ = x[msgPull-2]
	_ = x[msgGave-3]
}

const _msg_name = "msgPullerDonemsgGiverDonemsgPullmsgGave"

var _msg_index = [...]uint8{0, 13, 25, 32, 39}

func (i msg) String() string {
	if i < 0 || i >= msg(len(_msg_index)-1) {
		return "msg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _msg_name[_msg_index[i]:_msg_index[i+1]]
}
