#!/usr/bin/env bash

before=$(git diff --name-only)

go generate ./...
for f in $(find . -type f -name "*.go"); do
	goimports -w $f
done

after=$(git diff --name-only)

changed=0
for file in $(diff <(echo "$before") <(echo "$after") | grep -e '\.go$' | cut -b3-); do
	echo "Changed: $file"
	changed=1
done

exit "$changed"
